Bootstrap: docker
From: ubuntu:latest

%post
    apt-get update && apt-get -y install git wget

    apt-get -y install python3 python3-pip
    apt-get clean

    pip3 install numpy matplotlib scikit-learn
    pip3 install pandas
    pip3 install scipy
    pip3 install scikit-learn
    pip3 install nltk
    pip3 install xlrd
    pip3 install git+https://github.com/anjapago/flair

%environment
  SHELL=/bin/bash
  export SHELL

%runscript
    exec python3 flair_opt.py
