Bootstrap: shub
From: singularityhub/ubuntu

%runscript
    exec git clone https://github.com/anjapago/AnalyzeAccountability.git
    exec python3 AnalyzeAccountability/hello.py

%post
    apt-get update && apt-get -y install python3 git python3-pip wget
    apt-get install -y --force-yes python-dev python-numpy python-matplotlib
    pip install --upgrade pip
    pip install numpy
    pip install pandas
    pip install scipy
    pip install scikit-learn
    pip install nltk
