Bootstrap: shub
From: singularityhub/ubuntu

%runscript
    exec git clone https://github.com/anjapago/AnalyzeAccountability.git
    exec python3 AnalyzeAccountability/hello.py

%post
    apt-get update && apt-get -y install python3 git python3-pip wget
    pip3 install --upgrade pip3
    pip3 install numpy
    pip3 install pandas
    pip3 install scipy
    pip3 install scikit-learn
    pip3 install nltk
